### ISSUE TITLE
brise.SlackBuild的一点小问题

### ISSUE THREAD

**Issue by liuxueyang** [slackwarecn-slackbuilds/brise#1]
第101行`cd $PRGNAM-$PRGNAM-$VERSION`应该修改成：`cd $PRGNAM`

最后附上`brise-0.35.tar.gz`的下载地址：[brise-0.35.tar.gz](http://dl.bintray.com/lotem/rime/brise-0.35.tar.gz)

**Comment by nnnewb** [comment]
该次[提交](https://github.com/slackwarecn-slackbuilds/brise/commit/2d083c824cd72e15665d8bc5f766b3682e9aeab0)中已经修复，很抱歉直接复制了另一份SlackBuild而没有注意修改相关代码。
由于手里没有环境用于测试，请确认后直接关闭issue，有更多问题的话可以继续提出或提交pull request。
感谢提出问题。

**Comment by liuxueyang** [comment]
测试之后没有问题了。顺便问一下，https://github.com/rime/brise/archive/brise-0.35.tar.gz 这个地址是怎么找到的，去项目主页看了 https://github.com/rime/brise 找了好久没有找到。

**Comment by liuxueyang** [comment]
如果是从 https://github.com/rime/brise/archive/brise-0.35.tar.gz 下载的话，brise.SlackBuild文件的第101行就不用改了。

**Comment by nnnewb** [comment]
GitHub 网页点击 release。


发自网易邮箱大师
在2017年04月09日 05:12，LXY 写道：

测试之后没有问题了。顺便问一下，https://github.com/rime/brise/archive/brise-0.35.tar.gz 这个地址是怎么找到的，去项目主页看了 https://github.com/rime/brise 找了好久没有找到。

**Comment by liuxueyang** [comment]
原来如此，谢谢！
